// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAoRkpSm_9EhWse2Ws8XPLExD-xKymEANo',
    appId: '1:818345300890:web:c6576c983320217c67a023',
    messagingSenderId: '818345300890',
    projectId: 'daalupay-fdbaf',
    authDomain: 'daalupay-fdbaf.firebaseapp.com',
    storageBucket: 'daalupay-fdbaf.firebasestorage.app',
    measurementId: 'G-66X0SNC9ST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBE1SuDSBY9aSmJxAXWBJdf131urh23f9c',
    appId: '1:818345300890:android:1e976fbc1f45932b67a023',
    messagingSenderId: '818345300890',
    projectId: 'daalupay-fdbaf',
    storageBucket: 'daalupay-fdbaf.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDGRx73v4LNES_Ja-EmAH1qsiYG1bsAg7c',
    appId: '1:818345300890:ios:d3cfbfa16be2768467a023',
    messagingSenderId: '818345300890',
    projectId: 'daalupay-fdbaf',
    storageBucket: 'daalupay-fdbaf.firebasestorage.app',
    iosBundleId: 'com.daalupay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDGRx73v4LNES_Ja-EmAH1qsiYG1bsAg7c',
    appId: '1:818345300890:ios:d3cfbfa16be2768467a023',
    messagingSenderId: '818345300890',
    projectId: 'daalupay-fdbaf',
    storageBucket: 'daalupay-fdbaf.firebasestorage.app',
    iosBundleId: 'com.daalupay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAoRkpSm_9EhWse2Ws8XPLExD-xKymEANo',
    appId: '1:818345300890:web:0335710dcd18d7a767a023',
    messagingSenderId: '818345300890',
    projectId: 'daalupay-fdbaf',
    authDomain: 'daalupay-fdbaf.firebaseapp.com',
    storageBucket: 'daalupay-fdbaf.firebasestorage.app',
    measurementId: 'G-S4JBLZQB09',
  );
}
