// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDXeS6_s5OAJik-tUSgoTcRWYYCU-tYH9c',
    appId: '1:769091831615:web:6f550b6a52733e1908358a',
    messagingSenderId: '769091831615',
    projectId: 'daalupay-923ab',
    authDomain: 'daalupay-923ab.firebaseapp.com',
    storageBucket: 'daalupay-923ab.firebasestorage.app',
    measurementId: 'G-D81HC77K1E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkfHfJD00l3KwoHzVIdasaez9TlL6aPUc',
    appId: '1:769091831615:android:66c3ef835e2b80dd08358a',
    messagingSenderId: '769091831615',
    projectId: 'daalupay-923ab',
    storageBucket: 'daalupay-923ab.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuFRq2UdO2x6y_SewysLFuK5wvxyVia5U',
    appId: '1:769091831615:ios:441b5375977dfc8f08358a',
    messagingSenderId: '769091831615',
    projectId: 'daalupay-923ab',
    storageBucket: 'daalupay-923ab.firebasestorage.app',
    iosBundleId: 'com.daalupay',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDuFRq2UdO2x6y_SewysLFuK5wvxyVia5U',
    appId: '1:769091831615:ios:441b5375977dfc8f08358a',
    messagingSenderId: '769091831615',
    projectId: 'daalupay-923ab',
    storageBucket: 'daalupay-923ab.firebasestorage.app',
    iosBundleId: 'com.daalupay',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDXeS6_s5OAJik-tUSgoTcRWYYCU-tYH9c',
    appId: '1:769091831615:web:dba36c5f4f25b06a08358a',
    messagingSenderId: '769091831615',
    projectId: 'daalupay-923ab',
    authDomain: 'daalupay-923ab.firebaseapp.com',
    storageBucket: 'daalupay-923ab.firebasestorage.app',
    measurementId: 'G-52MVCPNJD8',
  );
}
